drop table if exists calculations cascade;

CREATE TABLE calculations
(
    id                int8 generated by default as identity unique,
    number_one        varchar(100),
    number_system_one INTEGER,
    number_two        varchar(100),
    number_system_two INTEGER,
    date              varchar(100),
    operation_name    varchar(100),
    primary key (id)
);
